# permissions for end users to view haegressgatewaypolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: cilium-ha-egress
    app.kubernetes.io/managed-by: kustomize
  name: haegressgatewaypolicy-viewer-role
rules:
- apiGroups:
  - cilium.angeloxx.ch
  resources:
  - haegressgatewaypolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cilium.angeloxx.ch
  resources:
  - haegressgatewaypolicies/status
  verbs:
  - get
