---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - cilium.angeloxx.ch
  resources:
  - haegressips
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cilium.angeloxx.ch
  resources:
  - haegressips/finalizers
  verbs:
  - update
- apiGroups:
  - cilium.angeloxx.ch
  resources:
  - haegressips/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cilium.io
  resources:
  - ciliumegressgatewaypolicies
  verbs:
  - get
  - list
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - patch
  - update
  - watch
