apiVersion: cilium.angeloxx.ch/v1alpha1
kind: haEgressGatewayPolicy
metadata:
  labels:
    app.kubernetes.io/name: cilium-ha-egress
    app.kubernetes.io/managed-by: kustomize
  name: haegressgatewaypolicy-sample
spec:
  # TODO(user): Add fields here
