{{ if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kube-vip-cilium-watcher.fullname" . }}-cr
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create","patch"]
  - apiGroups: ["cilium.io"]
    resources: ["ciliumegressgatewaypolicies"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  {{ end }}