name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.21.9' ]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Setup Ko
        uses: ko-build/setup-ko@v0.6

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Image
        env:
          IMAGE_REGISTRY_NAMESPACE: angeloxx
          IMAGE_REGISTRY: docker.io
          IMAGE_TAG_FORCED: latest
        run: |
          make build-image

      - name: Build Helm Chart
        env:
          IMAGE_REGISTRY_NAMESPACE: angeloxx
          IMAGE_REGISTRY: docker.io
          IMAGE_TAG_FORCED: latest
        run: |
          make build-helm-upload