name: Release
on:
  push:
    tags:
      - "v*"
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.21.9' ]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Setup Ko
        uses: ko-build/setup-ko@v0.6
      - name: Set up Kubeconform
        uses: bmuschko/setup-kubeconform@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Image
        env:
          IMAGE_REGISTRY_NAMESPACE: angeloxx
          IMAGE_REGISTRY: docker.io
        run: |
          make build-image

      - name: Build Helm Chart
        env:
          IMAGE_REGISTRY_NAMESPACE: angeloxx
          IMAGE_REGISTRY: docker.io
        run: |
          make helm
          make build-helm-upload

      - name: Extract version
        id: version
        run: |
          REF=${{ github.ref }}
          VERSION=${REF#refs/tags/v}
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            ${{ github.event.head_commit.message }}
            
            You can install the chart using the following command:
            ```shell
            helm upgrade -i cilium-haegress-operator --create-namespace --namespace cilium-haegress-operator oci://registry-1.docker.io/angeloxx/cilium-haegress-operator --version ${{ steps.version.outputs.VERSION }}
            ```

          draft: false
          prerelease: false